//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameFox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Игротека
    {
        public int Код_игротеки { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
        public string Время_начала { get; set; }
        public Nullable<int> Код_списка { get; set; }
        public string Количество_игроков { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Список Список { get; set; }
    }
}
