//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameFox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Игра
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Игра()
        {
            this.Турнир = new HashSet<Турнир>();
        }
    
        public int Код_игры { get; set; }
        public Nullable<int> Код_категории { get; set; }
        public Nullable<int> Код_жанра { get; set; }
        public Nullable<int> Код_тематики { get; set; }
        public string Наименование { get; set; }
        public string Возрастное_ограничение { get; set; }
        public string Описание { get; set; }
        public string Фото { get; set; }
        public Nullable<int> Код_списка { get; set; }
    
        public virtual Жанр Жанр { get; set; }
        public virtual Категории Категории { get; set; }
        public virtual Список Список { get; set; }
        public virtual Тематика Тематика { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Турнир> Турнир { get; set; }
    }
}
