//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameFox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Турнир
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Турнир()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код_турнира { get; set; }
        public string Наименование { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<int> Код_игры { get; set; }
        public Nullable<int> Код_мастера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        public virtual Игра Игра { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
